### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [czechboy0/SecretSocks#2]
There are some devs who still don't know how to use SPM 😢 
It would be cool to add the *Manual installation* guide in your ```README.md```. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by czechboy0** [comment]
I see, however this repo has dependencies which themselves might have dependencies. So manual installation would mean cloning this repository, all its dependencies in turn etc.  Thus I didn't add explicit manual installation steps.

Here's SwiftPM documentation, including how to get started: https://swift.org/package-manager/

If you have Xcode 8 beta 1, you already have SwiftPM. Switch to use that new Xcode on the command line and then, in a new folder, run `swift package init --type=library`, which creates a skeleton of a new project. In the `Package.swift` file, make sure you have:

```
let package = Package(name: "YOUR_PACKAGE_NAME",
dependencies: [
.Package(url: "https://github.com/czechboy0/SecretSocks.git", majorVersion: 0, minor: 1)
])
```

and then run `swift build`, which pulls and compiles your project. Pulled dependencies will be in the `Packages` folder.
